version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5057:80"
    container_name: app-product-consumer-api
    networks:
      - personal-network
    volumes:
      - product-volume:/App/data

networks:
  personal-network:
    external: true

volumes:
  product-volume:
    external: true
