apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-consumer
  template:
    metadata:
      labels:
        app: product-consumer
    spec:
      containers:
      - name: product-consumer
        image: product-consumer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: hackatoon-product-config
