apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-afm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-afm
  template:
    metadata:
      labels:
        app: rabbitmq-afm
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - containerPort: 5672
          - containerPort: 15672
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_DEFAULT_USER
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_DEFAULT_PASS